In [1]:
#构造一个没有任何参数的自定义层
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y = net(torch.rand(4,8))
Y.mean()

tensor(9.3132e-09, grad_fn=<MeanBackward0>)

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[ 0.4496, -1.2259, -0.5277],
        [-1.3941, -0.2957,  2.5251],
        [-1.0643,  1.3147, -0.5746],
        [ 0.8255,  0.3080,  0.5750],
        [ 0.8652, -2.1070, -1.8658]], requires_grad=True)

In [8]:
# 读写文件
# 加载和保存张量
x = torch.arange(4)
torch.save(x, 'x-file')

In [9]:
x2 = torch.load('x-file')

In [10]:
x2

tensor([0, 1, 2, 3])

In [11]:
# 存储一个张量列表
y = torch.zeros(4)
torch.save([x,y], 'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [12]:
# 写入或读取从字符串映射到张量的字典
mydict = {'x':x, 'y':y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [13]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.output = nn.Linear(256,10)
        
    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))
    
net = MLP()
X = torch.randn(size=(2,20))
Y = net(X)

In [14]:
torch.save(net.state_dict(),'mlp.params')

In [18]:
clone = MLP()
clone.load_state_dict(torch.load("mlp.params"))
clone.eval()
#clone

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [19]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])