In [1]:
import torch

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

In [5]:
len(x)

4

In [6]:
A = torch.arange(20).reshape(5, 4)

In [7]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [10]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [12]:
# 两个矩阵按元素乘法称为 哈达玛积（Hadamard Product) 
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [14]:
# 计算其元素的和
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [27]:
# 任意形状张量的和
A = torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)

In [16]:
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [17]:
float(A.sum())

780.0

In [18]:
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [19]:
A.sum(axis=0)

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [20]:
A.sum(axis=1)

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])

In [21]:
A.sum(axis=2)

tensor([[  6,  22,  38,  54,  70],
        [ 86, 102, 118, 134, 150]])

In [22]:
A.sum(axis=[0, 1])

tensor([180, 190, 200, 210])

In [24]:
A.sum(axis=[1,0])

tensor([180, 190, 200, 210])

In [28]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [35]:
# 计算总和或均值时保持轴数不变
sum_A = A.sum(axis=1, keepdim=True)
sum_A, A, sum_A.shape, A.shape

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 1, 4]),
 torch.Size([2, 5, 4]))

In [33]:
# 通过广播将A除以sum_A
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [36]:
#某个轴计算A元素的累积总和
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [37]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [38]:
torch.sum(x * y)

tensor(6.)

In [44]:
# 矩阵向量积 Ax 是一个长度为m的列向量， 其ith元素是点积aiT x
B = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [45]:
B.shape, x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [47]:
B, x, torch.mv(B, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [48]:
C = torch.ones((4,3), dtype=torch.float32)

In [49]:
C

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [50]:
torch.mm(B,C)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [51]:
# 范数
u = torch.tensor([3., -4])
torch.norm(u)

tensor(5.)

In [52]:
# L1范数，表示向量元素的绝对值求和
torch.abs(u).sum()

tensor(7.)

In [53]:
# 矩阵范数 F范数 Frobenius norm
torch.norm(torch.ones(4,9))

tensor(6.)