In [1]:
# 多输入多输出通道
import torch
import numpy as np
from d2l import torch as d2l

In [3]:
def corr2d_multi_in(X, K):
    return sum(d2l.corr2d(x, k) for x, k in zip(X, K))

In [9]:
x = torch.tensor(np.append(np.arange(9),np.arange(1, 10)))

In [50]:
# zip 的用法
a = ['a', 'b', 'c', 'd']
b = [1, 2, 3, 4]
l = list(zip(a, b))
origin1, origin2 = zip(*l)
print(l)
print(list(origin1))

d = dict(zip(a,b))
print(d)

[('a', 1), ('b', 2), ('c', 3), ('d', 4)]
['a', 'b', 'c', 'd']
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [57]:
# dict用法

# 增
d['a'] = 1
d['e'] = 5
print(d)

# 删
del d['a']
print(d)

# 改
d['d'] = 10
print(d)

# 查
print(d['c'])

{'b': 2, 'c': 3, 'd': 4, 'e': 5, 'a': 1}
{'b': 2, 'c': 3, 'd': 4, 'e': 5}
{'b': 2, 'c': 3, 'd': 10, 'e': 5}
3


In [19]:
x = x.float()

In [20]:
x.reshape(2,3,3)

tensor([[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [21]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
X.shape

torch.Size([2, 3, 3])

In [17]:
X

tensor([[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [26]:
K = torch.tensor(np.append(np.arange(4),np.arange(1,5))).reshape(2,2,2).float()

In [27]:
K

tensor([[[0., 1.],
         [2., 3.]],

        [[1., 2.],
         [3., 4.]]])

In [28]:
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

In [29]:
K

tensor([[[0., 1.],
         [2., 3.]],

        [[1., 2.],
         [3., 4.]]])

In [31]:
corr2d_multi_in(X, K).shape

torch.Size([2, 2])

In [58]:
def corr2d_multi_in_out(X, K):
    return torch.stack([corr2d_multi_in(X,k) for k in K], 0)
K = torch.stack((K, K + 1, K + 2), 0)
K.shape

torch.Size([3, 2, 2, 2])

In [59]:
K

tensor([[[[0., 1.],
          [2., 3.]],

         [[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]],

         [[2., 3.],
          [4., 5.]]],


        [[[2., 3.],
          [4., 5.]],

         [[3., 4.],
          [5., 6.]]]])

In [60]:
corr2d_multi_in_out(X,K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [61]:
corr2d_multi_in_out(X,K).shape

torch.Size([3, 2, 2])

In [65]:
# 1*1 卷积
def corr2d_multi_in_out_1x1(X,K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape(c_o, c_i)
    Y = torch.matmul(K, X)
    return Y.reshape((c_o, h, w))

X = torch.normal(0, 1,(3, 3, 3))
K = torch.normal(0, 1,(2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)

assert float(torch.abs(Y1 - Y2).sum())<1e-6