In [1]:
import torch
from torch import nn
from d2l import torch as d2l
import numpy as np

In [3]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1, X.shape[1] - p_w + 1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()
    return Y

In [12]:
X = torch.tensor(np.arange(9)).float().reshape(-1,3)
print(X)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [13]:
pool2d(X, (2,2))

tensor([[4., 5.],
        [7., 8.]])

In [14]:
pool2d(X, (2,2), mode='avg')

tensor([[2., 3.],
        [5., 6.]])

In [16]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

# 填充和步幅
## 深度学习框架中的步幅与池化窗口大小相同

In [22]:
pool2d = nn.MaxPool2d(3) # 3*3的窗口
pool2d = nn.MaxPool2d(3,stride=1) # 3*3的窗口
pool2d = nn.MaxPool2d(3,stride=1,padding=1) # 3*3的窗口

In [18]:
nn.MaxPool2d?

In [23]:
pool2d(X)

tensor([[[[ 5.,  6.,  7.,  7.],
          [ 9., 10., 11., 11.],
          [13., 14., 15., 15.],
          [13., 14., 15., 15.]]]])

## 池化层在每个输入通道上单独运算

In [34]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [35]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])