In [1]:
import torch

In [2]:
# 张量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel() # 元素的种数

12

In [5]:
x = x.reshape(-1,3)

In [6]:
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [7]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
a = torch.tensor([[2,1,3,4],[1,2,3,4],[4,3,2,1]])
a

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [12]:
a.shape

torch.Size([3, 4])

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y ## **是幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
# 把张量连结在一起
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3],[1,2,3,4],[4,3,2,1]])
torch.cat((X, Y),dim=0), torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
# 广播机制
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [21]:
# 把 a 复制成3*2 把b复制成 3*2 
# 即 把1 变了
c = torch.cat((a,a),dim=1)
d = torch.cat((b,b,b),dim=0)
c, d

(tensor([[0, 0],
         [1, 1],
         [2, 2]]),
 tensor([[0, 1],
         [0, 1],
         [0, 1]]))

In [22]:
c + d

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [24]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [25]:
# 区域赋值
X
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [29]:
# 如何避免内存过大
before = id(Y) # 可把id理解为指针
Y = Y + X
id(Y) == before

False

In [30]:
#执行原地操作
z = torch.zeros_like(Y)
print('id(z):', id(z))
z[:] = X + Y
print('id(z):', id(z))

id(z): 2031789534080
id(z): 2031789534080


In [31]:
# 如果后续计算中没有重复使用x
before = id(Y) # 可把id理解为指针
Y[:] = Y + X
id(Y) == before

True

In [33]:
#转换为NumPy
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [34]:
# 将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a, a.item(),float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)